{% set name = "pytest-bdd" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 20ce2519fc5fe08a74d160aba52d6e5e46d99da949bc929591eefd063a8e573b

build:
  noarch: python
  number: 0
  entry_points:
    - pytest-bdd = pytest_bdd.scripts:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - glob2
    - mako
    - parse
    - parse_type
    - py
    - pytest >=3.0.0
    - six >=1.9.0

test:
  imports:
    - pytest_bdd
  commands:
    - pytest-bdd --help

about:
  home: https://github.com/pytest-dev/pytest-bdd
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: BDD for pytest
  description: pytest-bdd implements a subset of the Gherkin language to enable automating project requirements testing and to facilitate behavioral driven development.
  dev_url: https://github.com/pytest-dev/pytest-bdd
  doc_url: https://github.com/pytest-dev/pytest-bdd

extra:
  recipe-maintainers:
    - breathe
