{% set name = "pytest-bdd" %}
{% set version = "7.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b992536360f49441ac25b687f092d02815582b60b2acb3f62fce16b7b6e7273d

build:
  noarch: python
  number: 0
  entry_points:
    - pytest-bdd = pytest_bdd.scripts:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - mako
    - parse
    - parse_type
    - pytest >=6.2.0
    - typing-extensions

test:
  imports:
    - pytest_bdd
  commands:
    - pytest-bdd --help

about:
  home: https://github.com/pytest-dev/pytest-bdd
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: BDD for pytest
  description: pytest-bdd implements a subset of the Gherkin language to enable automating project requirements testing and to facilitate behavioral driven development.
  dev_url: https://github.com/pytest-dev/pytest-bdd
  doc_url: https://github.com/pytest-dev/pytest-bdd

extra:
  recipe-maintainers:
    - m0nonoke
    - PertuyF
    - breathe
